spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.110.34.2:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: LXLxby*j0472




logging:
  level:
    root: warn
    com.lxl: info
  file:
    name: log/blog-pro.log

