spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro
  messages:
    basename: i18n/messages

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lxl.pojo
 # configuration:
 #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

comment.avatar: /images/avatar.png
